org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.77
neo_version_range=[26.2.0.77,)

mod_id=wateroptimisation
mod_name=Water Optimisation
mod_license=MIT
mod_version=0.0.8.1
mod_group_id=io.github.imcinq.wateroptimisation
