license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/imCinq/water-optimisation"
authors="imCinq"
description='''A client-side Minecraft optimization mod for water-heavy scenes.'''
displayTest="IGNORE_SERVER_VERSION"

[[mixins]]
config="wateroptimisation.neoforge.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
